version: 2.1

workflows:
  version: 2
  build-and-test:
    jobs:
      - go-build-and-test
      - nix-build-and-test-stable
      - nix-build-and-test-unstable
  nix-periodic-build:
    triggers:
      - schedule:
          cron: '42 2 * * 1'
          filters:
            branches:
              only:
                - master
    jobs:
      - nix-build-and-test-stable
      - nix-build-and-test-unstable

jobs:
  go-build-and-test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - run:
          name: setup environment
          command: echo 'CGO_ENABLED=0' >> $BASH_ENV
      - checkout
      - run: go build
      - run: go test -v ./...

  nix-build-and-test-stable:
    docker:
      - image: nixos/nix:latest
    steps:
      - checkout
      - run: nix-build -I nixpkgs=channel:nixos-21.05

  nix-build-and-test-unstable:
    docker:
      - image: nixos/nix:latest
    steps:
      - checkout
      - run: nix-build -I nixpkgs=channel:nixos-unstable
